---
files:
- source: "/app/values/test.json"
  dest: "/app/values/test.csv"
  first_line_contains_header: true
  scheme: identifier,source_phrase,nl
  multilingual_spreadsheet : true
  translation: "/app/values-%two_letters_code%/%original_file_name%"
