files:
  - source: /app/values/*.xml
    translation: /app/%file_name%.%two_letters_code%.xml
    translate_content: 0
    translate_attributes: 0
    content_segmentation: 0
    dest: /app/values/test.resw
