---
files:
- source: "/app/values/test.md"
  # dest: "/app/values/test.csv"
  # first_line_contains_header: true
  # scheme: identifier,source_phrase,nl,uk
  # multilingual_spreadsheet : true
  translation: "/app/values-%two_letters_code%/%original_file_name%"
